BASE <http://onto.fel.cvut.cz/voc/ata-100/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ata: <http://onto.fel.cvut.cz/voc/ata-100/>
CONSTRUCT{
 ?g rdfs:label ?chapter_label;
	ata:has-id ?chapter_id;
	rdfs:comment ?chapter_description.
}WHERE {
  BIND(IRI(concat("http://onto.fel.cvut.cz/voc/ata-100/ata-", ?chapter_id)) as ?g)
}
